# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Krishnendu"
title_separator          : "-"
name                     : &name "N. V. Krishnendu"
description              : &description "Krishnendu's academic profile"
url                      : "https://krishnendugit.github.io"
baseurl                  : "/nv-krishnendu"
repository               : "KrishnenduGit/nv-krishnendu"

# Site Author
author:
  avatar           : "profile.png"
  name             : "N. V. Krishnendu"
  pronouns         :
  bio              : "I am a senior gravitational wave research fellow specialising in tests of General Relativity, compact-object physics and astrophysics, waveform modelling, and gravitational wave data analysis."
  location         : "United Kingdom"
  employer         : "University of Birmingham"
  uri              :
  email            : "nv.krishnendu@ligo.org"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "KrishnenduGit"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine              :
  weibo             :
  wikipedia        :
  xing             :
  youtube           :
  zhihu            :


# Reading Files
include:
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor
