# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Krishnendu"
title_separator          : "-"
name                     : &name "N. V. Krishnendu"
description              : &description "Krishnendu's academic profile"
url                      : "https://krishnendugit.github.io"
baseurl                  : "/nv-krishnendu"
repository               : "KrishnenduGit/nv-krishnendu"

# Site Author
author:
  avatar           : "profile.png"
  name             : "N. V. Krishnendu"
  pronouns         :
  bio              : "I am a senior gravitational wave research fellow specialising in tests of General Relativity, compact-object physics and astrophysics, waveform modelling, and gravitational wave data analysis. A member of the LIGO Scientific Collaboration since 2017, I have contributed to major analyses and, since January 2025, I am co-chairing the fundamental physics Working Group. I lead the Cosmic Explorer Science Trace-ability Studies, and one of the three coordinators of the fundamental physics division of Einstein Telescope Collaboration's Observational Science Board. My research focuses on inferring the astrophysical properties of compact binaries using current and next-generation detectors, and I contribute to science-case studies for CE, ET, LISA, and LGWA."
  location         : "United Kingdom"
  employer         : "University of Birmingham"
  uri              :
  email            : "nv.krishnendu@ligo.org"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "KrishnenduGit"
  kaggle           :
  stackoverflow    :

  # Social media
 linkedin         :
 instagram        :
